export const API = {
  questions: [
    {
      id: 3,
      name: "Preferência",
      text: "A empresa-teste é minha primeira opção",
      order: 3,
      option_set: [
        {
          id: 12,
          text: "Concordo totalmente",
          option_type: "STRONGLY_AGREE",
          order: 1,
          question: 3,
        },
        {
          id: 13,
          text: "Concordo",
          option_type: "AGREE",
          order: 2,
          question: 3,
        },
        {
          id: 14,
          text: "Não concordo e nem discordo",
          option_type: "NOT_AGREE_NOT_DISAGREE",
          order: 3,
          question: 3,
        },
        {
          id: 15,
          text: "Discordo",
          option_type: "DISAGREE",
          order: 4,
          question: 3,
        },
        {
          id: 16,
          text: "Discordo totalmente",
          option_type: "STRONGLY_DISAGREE",
          order: 5,
          question: 3,
        },
      ],
    },
    {
      id: 4,
      name: "Relevância",
      text: "A empresa-teste está presente de forma relevante na minha vida.",
      order: 4,
      option_set: [
        {
          id: 17,
          text: "Concordo totalmente",
          option_type: "STRONGLY_AGREE",
          order: 1,
          question: 4,
        },
        {
          id: 18,
          text: "Concordo",
          option_type: "AGREE",
          order: 2,
          question: 4,
        },
        {
          id: 19,
          text: "Não concordo e nem discordo",
          option_type: "NOT_AGREE_NOT_DISAGREE",
          order: 3,
          question: 4,
        },
        {
          id: 20,
          text: "Discordo",
          option_type: "DISAGREE",
          order: 4,
          question: 4,
        },
        {
          id: 21,
          text: "Discordo totalmente",
          option_type: "STRONGLY_DISAGREE",
          order: 5,
          question: 4,
        },
      ],
    },
    {
      id: 5,
      name: "Reputação",
      text: "Estar associado à empresa-teste faz bem para a minha imagem pessoal.",
      order: 5,
      option_set: [
        {
          id: 22,
          text: "Concordo totalmente",
          option_type: "STRONGLY_AGREE",
          order: 1,
          question: 5,
        },
        {
          id: 23,
          text: "Concordo",
          option_type: "AGREE",
          order: 2,
          question: 5,
        },
        {
          id: 24,
          text: "Não concordo e nem discordo",
          option_type: "NOT_AGREE_NOT_DISAGREE",
          order: 3,
          question: 5,
        },
        {
          id: 25,
          text: "Discordo",
          option_type: "DISAGREE",
          order: 4,
          question: 5,
        },
        {
          id: 26,
          text: "Discordo totalmente",
          option_type: "STRONGLY_DISAGREE",
          order: 5,
          question: 5,
        },
      ],
    },
    {
      id: 2,
      name: "Elasticidade",
      text: "Eu experimentaria novos produtos da empresa-teste?",
      order: 6,
      option_set: [
        {
          id: 7,
          text: "Concordo totalmente",
          option_type: "STRONGLY_AGREE",
          order: 1,
          question: 2,
        },
        {
          id: 8,
          text: "Concordo",
          option_type: "AGREE",
          order: 2,
          question: 2,
        },
        {
          id: 9,
          text: "Não concordo e nem discordo",
          option_type: "NOT_AGREE_NOT_DISAGREE",
          order: 3,
          question: 2,
        },
        {
          id: 10,
          text: "Discordo",
          option_type: "DISAGREE",
          order: 4,
          question: 2,
        },
        {
          id: 11,
          text: "Discordo totalmente",
          option_type: "STRONGLY_DISAGREE",
          order: 5,
          question: 2,
        },
      ],
    },
    {
      id: 1,
      name: "Score",
      text: "O quanto você apoia o sucesso da empresa-teste?",
      order: 7,
      option_set: [
        {
          id: 1,
          text: "Apoio ativamente",
          option_type: "STRONGLY_SUPPORT",
          order: 1,
          question: 1,
        },
        {
          id: 2,
          text: "Apoio",
          option_type: "SUPPORT",
          order: 2,
          question: 1,
        },
        {
          id: 3,
          text: "Apoio em parte",
          option_type: "PARTIALLY_SUPPORT",
          order: 3,
          question: 1,
        },
        {
          id: 4,
          text: "Sou neutro",
          option_type: "NEUTRAL",
          order: 4,
          question: 1,
        },
        {
          id: 5,
          text: "Não apoio",
          option_type: "NOT_SUPPORT",
          order: 5,
          question: 1,
        },
        {
          id: 6,
          text: "Sou contra",
          option_type: "AGAINST",
          order: 6,
          question: 1,
        },
      ],
    },
    {
      id: 6,
      name: "Explicação Score",
      text: "Quer explicar sua resposta? (opcional)",
      order: 8,
      option_set: [
        {
          id: 27,
          text: "''",
          option_type: "OPEN_TEXT",
          order: 1,
          question: 6,
        },
      ],
    },
  ],
};
